# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301998c7b0ca1020496672340c582e1b38bb0a163f6d3d01a7603f68ae069b67ea8f0076937fc3511d31f1101dcaf2f26a393f21ef1f62f8052aac732476a3be

test:
  secret_key_base: edab29fddc2a23e1d37707f9e9fcba61a1fa9156677347719d2cacbd101f796ca663a4be560fd6cfe6e35816851564c6aabf61714a6bb9a82c7ad01eef33202c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
